add-docker
aleshchenko37/java-shareit pull request #4
Opened 2023-11-18 17:44 UTC by aleshchenko37

2023-11-19 08:15 UTC, VadimZharkov commented on server/src/main/resources/schema.sql
> -CREATE TYPE IF NOT EXISTS status AS ENUM ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED');
А тип статус в СУБД зачем убрала)?  Допустимы конечно оба варианта и  кастомный тип и строка, но с типом интересней на мой взгляд.

2023-11-19 08:16 UTC, VadimZharkov requested changes
Из всех контроллеров сервера нужно убрать валидацию (@Valid), т.к. валидирует по ТЗ gataway. Он все плохое отсечет.

2023-11-20 10:40 UTC, aleshchenko37 commented on server/src/main/resources/schema.sql
> -CREATE TYPE IF NOT EXISTS status AS ENUM ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED');
Из-за перехода с базы h2 на postgresql конструкция if not exists перестала работать. Если ее убрать, получаю ошибки преобразования типов. Не смогла решить этот вопрос, даже с наставником(((

2023-11-21 06:56 UTC, VadimZharkov commented on server/src/main/resources/schema.sql
> -CREATE TYPE IF NOT EXISTS status AS ENUM ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED');
А да припоминаю, есть такая проблема. Немного на другом стеке (тоже спринг, но другой набор зависимостей) решал след. образом:
1) в корень проекта добавляем файл init.sql
в нем пишем
DO $$ BEGIN
    CREATE TYPE status AS ENUM ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

2) в докер-компоуз в постгрес добавляем строчку  
 volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

тем самым в постргес при старте контейнера создастся нужный нам тип. т.е. не спрингом его создаем (раз не работает), а докером.

2023-11-21 06:56 UTC, VadimZharkov approved these changes

2023-11-21 12:51 UTC, merged